package edu.eci.cosw.polizas.entidades;
// Generated Aug 20, 2014 7:58:33 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="CLIENTES")
public class Cliente  implements java.io.Serializable {


     private ClientesId id;
     private String nombre;
     private String direccion;
     private String telefono;
     private Set<PolizaAprobada> polizasAprobadases = new HashSet<PolizaAprobada>(0);

    public Cliente() {
    }

	
    public Cliente(ClientesId id, String nombre, String direccion, String telefono) {
        this.id = id;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Cliente(ClientesId id, String nombre, String direccion, String telefono, Set polizasAprobadases) {
       this.id = id;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.polizasAprobadases = polizasAprobadases;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="tipoId", column=@Column(name="tipo_id", nullable=false, length=3) ) } )
    public ClientesId getId() {
        return this.id;
    }
    
    public void setId(ClientesId id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumns(value = {@JoinColumn(name = "CLIENTES_id",referencedColumnName = "id"),@JoinColumn(name = "CLIENTES_tipo_id",referencedColumnName = "tipo_id")})    
    public Set<PolizaAprobada> getPolizasAprobadases() {
        Set<PolizaAprobada> pa=this.polizasAprobadases;
        return pa;
    }
    
    public void setPolizasAprobadases(Set<PolizaAprobada> polizasAprobadases) {
        this.polizasAprobadases = polizasAprobadases;
    }




}


