package edu.eci.cosw.polizas.entidades;
// Generated Aug 20, 2014 7:58:33 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientesId generated by hbm2java
 */
@Embeddable
public class ClientesId  implements java.io.Serializable {


     private int id;
     private String tipoId;

    public ClientesId() {
    }

    public ClientesId(int id, String tipoId) {
       this.id = id;
       this.tipoId = tipoId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="tipo_id", nullable=false, length=3)
    public String getTipoId() {
        return this.tipoId;
    }
    
    public void setTipoId(String tipoId) {
        this.tipoId = tipoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientesId) ) return false;
		 ClientesId castOther = ( ClientesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getTipoId()==castOther.getTipoId()) || ( this.getTipoId()!=null && castOther.getTipoId()!=null && this.getTipoId().equals(castOther.getTipoId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getTipoId() == null ? 0 : this.getTipoId().hashCode() );
         return result;
   }   


}


